# Generated by Django 4.0.6 on 2022-07-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=56)),
                ('slug', models.SlugField(max_length=56)),
                ('is_menu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlec', models.CharField(max_length=512)),
                ('date', models.DateField(auto_now_add=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.category')),
            ],
        ),
    ]
