# Generated by Django 4.0.6 on 2022-07-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titlec',
            new_name='title',
        ),
    ]
